export enum ChatEvents {
    Connect = 'connect',
    Message = 'message',
    JoinRoomSolo = 'joinRoomSolo',
    LeaveRoom = 'leaveRoom',
    ServerTime = 'serverTime',
    StopTimer = 'stopTimer',
    SendRoomName = 'sendRoomName',
    Hello = 'hello',
    GameEnded = 'gameEnded',
    StartMultiGame = 'startMultiGame',
    FindDifference = 'findDifference',
    FeedbackDifference = 'feedbackDifference',
    SendGiveUp = 'sendGiveUp',
    GameName = 'gameName',
    MousePosition = 'mousePosition',
    StartTimeLimit = 'startTimeLimit',
    StartMultiTimeLimit = 'startMultiTimeLimit',
    ModifyTime = 'modifyTime'
}
