export enum ChatEvents {
    Connect = 'connect',
    Message = 'message',
    Validate = 'validate',
    BroadcastAll = 'broadcastAll',
    JoinRoom = 'joinRoom',
    RoomMessage = 'roomMessage',
    MassMessage = 'massMessage',
    Hello = 'hello',
    Clock = 'clock',
    Timer = 'timer',
    Hint = 'hint',
    Error = 'error',
    DifferenceFound = 'found',
}
